"""empty message

Revision ID: 030751b25118
Revises: 4a20339c1e22
Create Date: 2017-11-16 19:27:30.131681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '030751b25118'
down_revision = '4a20339c1e22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['email'])
    op.create_unique_constraint(None, 'users', ['username'])
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
